# -*- coding: utf-8 -*-
"""backup3icsus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hlr82b9eOlNe9h9FynwG2PhISojhJqko
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go

"""***
# <font size = 12 color = royalblue> FUNÇÕES </font>
***
"""

def percapita(df, pop_capitais):

    # extrai código IBGE da capital
    df["codigo"] = df["Capital"].str.extract(r"(\d{6})")

    # dataframe da população
    pop_df = pd.DataFrame({
        "codigo": list(pop_capitais.keys()),
        "pop": list(pop_capitais.values())
    })

    # merge pelo código
    df = df.merge(pop_df, on="codigo", how="inner")

    # remove colunas que não são números
    df_num = df.drop(columns=["Capital","Total","pop","codigo"], errors="ignore")

    # limpa valores
    df_num = df_num.replace("-",0).astype(float)

    # calcula per capita
    df_num = df_num.div(df["pop"], axis=0) * 100000

    # usa codigo como índice
    df_num.index = df["codigo"]

    return df_num

def plot_linhas(dfs, nome_df, capitais):

    df = dfs[nome_df]

    fig = go.Figure()

    for i in range(len(df)):

        codigo = df.index[i]
        nome = capitais.get(codigo, codigo)

        fig.add_trace(
            go.Scatter(
                x=df.columns,
                y=df.iloc[i],
                mode="lines",
                name=nome
            )
        )

    fig.update_layout(
        title=f"DADOS SUSU - {nome_df}",
        xaxis_title="Tempo",
        yaxis_title="Atendimentos por 100k hab",
        width=1200,
        height=700
    )

    return fig

def plot_barras(dfs, nome_df, capitais):

    df = dfs[nome_df]

    fig = go.Figure()

    for i in range(len(df)):

        codigo = str(df.index[i])
        nome = capitais.get(codigo, codigo)

        fig.add_trace(
            go.Bar(
                x=df.columns,
                y=df.iloc[i],
                name=nome,
                visible=(i == 0)
            )
        )

    buttons = []

    for i in range(len(df)):

        codigo = str(df.index[i])
        nome = capitais.get(codigo, codigo)

        visible = [False] * len(df)
        visible[i] = True

        buttons.append(
            dict(
                label=nome,
                method="update",
                args=[
                    {"visible": visible},
                    {"title": f"DADOS SUS - {nome}"}
                ]
            )
        )

    fig.update_layout(
        updatemenus=[dict(active=0, buttons=buttons)],
        title=f"DADOS SUS - {nome_df}",
        xaxis_title="Tempo",
        yaxis_title="Atendimentos por 100k hab",
        width=1200,
        height=700
    )

    return fig

def plot_barras_stack(dfs, nome_df, capitais):

    df = dfs[nome_df]

    fig = go.Figure()

    for i in range(len(df)):

        codigo = str(df.index[i])
        nome = capitais.get(codigo, codigo)

        fig.add_trace(
            go.Bar(
                x=df.columns,
                y=df.iloc[i],
                name=nome
            )
        )

    fig.update_layout(
        title=f"DADOS SUS - {nome_df}",
        xaxis_title="Tempo",
        yaxis_title="Atendimentos por 100k hab",
        barmode="stack",
        width=1200,
        height=700
    )

    return fig

def plot_heatmap(dfs, nome_df, capitais):

    df = dfs[nome_df]

    nomes = [capitais.get(str(c), str(c)) for c in df.index]

    fig = go.Figure(
        data=go.Heatmap(
            z=df.values,
            x=df.columns,
            y=nomes,
            colorscale="turbo"
        )
    )

    fig.update_layout(
        title=f"DADOS SUS - {nome_df}",
        xaxis_title="Tempo",
        yaxis_title="Capital",
        width=1200,
        height=700
    )

    return fig

def plot_area(dfs, nome_df, capitais):

    df = dfs[nome_df]

    fig = go.Figure()

    for i in range(len(df)):

        codigo = str(df.index[i])
        nome = capitais.get(codigo, codigo)

        fig.add_trace(
            go.Scatter(
                x=df.columns,
                y=df.iloc[i],
                mode="lines",
                stackgroup="one",
                name=nome
            )
        )

    fig.update_layout(
        title=f"DADOS SUS - {nome_df}",
        xaxis_title="Tempo",
        yaxis_title="Atendimentos por 100k hab",
        width=1200,
        height=700
    )

    return fig

def plot_todos(dfs, capitais):
    graficos = ["meses20182020", "meses20232024", "meses_total", "anos_total"]



    for g in graficos:
      print("Linhas")
      plot_linhas(dfs, g, capitais)
    for g in graficos:
      print("Barras")
      plot_barras(dfs, g, capitais)
    for g in graficos:
      print("Barras empilhadas")
      plot_barras_stack(dfs, g, capitais)
    for g in graficos:
      print("Heatmap")
      plot_heatmap(dfs, g, capitais)
    for g in graficos:
      print("Área")
      plot_area(dfs, g, capitais)

"""***
# <font size = 12 color = royalblue> ABERTURA DOS DADOS </font>
***
"""

pop_capitais = {
"110020": 517709,
"120040": 389001,
"130260": 2303732,
"140010": 485477,
"150140": 1397315,
"160030": 489676,
"172100": 328499,
"211130": 1089215,
"221100": 905692,
"230440": 2578483,
"240810": 784249,
"250750": 897633,
"261160": 1588376,
"270430": 994952,
"280030": 630932,
"292740": 2564204,
"310620": 2415872,
"320530": 343378,
"330455": 6730729,
"355030": 11904961,
"410690": 1830795,
"420540": 587486,
"431490": 1388794,
"500270": 962883,
"510340": 691875,
"520870": 1503256,
"530010": 2996899
}

cod_capitais = {
"110020": "Porto Velho",
"120040": "Rio Branco",
"130260": "Manaus",
"140010": "Boa Vista",
"150140": "Belém",
"160030": "Macapá",
"172100": "Palmas",
"211130": "São Luís",
"221100": "Teresina",
"230440": "Fortaleza",
"240810": "Natal",
"250750": "João Pessoa",
"261160": "Recife",
"270430": "Maceió",
"280030": "Aracaju",
"292740": "Salvador",
"310620": "Belo Horizonte",
"320530": "Vitória",
"330455": "Rio de Janeiro",
"355030": "São Paulo",
"410690": "Curitiba",
"420540": "Florianópolis",
"431490": "Porto Alegre",
"500270": "Campo Grande",
"510340": "Cuiabá",
"520870": "Goiânia",
"530010": "Brasília"
}

"""SAMU 192:ATENDIMENTO DAS CHAMADAS RECEBIDAS PELA CENTRAL DE REGULAÇÃO DAS URGÊNCIAS"""

dados1 = "https://raw.githubusercontent.com/JoaoVGuerra06/PesquisaDataSus/main/SAMU%20192%3AATENDIMENTO%20DAS%20CHAMADAS%20RECEBIDAS%20PELA%20CENTRAL%20DE%20REGULACAO%20DAS%20URGENCIAS/anos20182020.csv"

dados2 = "https://raw.githubusercontent.com/JoaoVGuerra06/PesquisaDataSus/main/SAMU%20192%3AATENDIMENTO%20DAS%20CHAMADAS%20RECEBIDAS%20PELA%20CENTRAL%20DE%20REGULACAO%20DAS%20URGENCIAS/anos20232024.csv"

dados3 = "https://raw.githubusercontent.com/JoaoVGuerra06/PesquisaDataSus/main/SAMU%20192%3AATENDIMENTO%20DAS%20CHAMADAS%20RECEBIDAS%20PELA%20CENTRAL%20DE%20REGULACAO%20DAS%20URGENCIAS/meses20182020.csv"

dados4 = "https://raw.githubusercontent.com/JoaoVGuerra06/PesquisaDataSus/main/SAMU%20192%3AATENDIMENTO%20DAS%20CHAMADAS%20RECEBIDAS%20PELA%20CENTRAL%20DE%20REGULACAO%20DAS%20URGENCIAS/meses20232024.csv"



links = [
dados1,
dados2,
dados3,
dados4
]


df_tot1 = {}
dfs1 = {}

for link in links:

    nome = link.split("/")[-1].replace(".csv","")

    df = pd.read_csv(link, sep=";", skiprows=5, encoding="latin1")

    df_tot1[nome] = df
    dfs1[nome] = percapita(df, pop_capitais)


dfs1["anos_total"] = pd.concat(
    [df for nome, df in dfs1.items() if "ano" in nome],
    axis=1
)

dfs1["meses_total"] = pd.concat(
    [df for nome, df in dfs1.items() if "mes" in nome],
    axis=1
)

dfs1["anos_total"] = dfs1["anos_total"].loc[:, ~dfs1["anos_total"].columns.duplicated()]
dfs1["meses_total"] = dfs1["meses_total"].loc[:, ~dfs1["meses_total"].columns.duplicated()]


for nome, df in dfs1.items():
    print(nome, len(df))

"""SAMU 192: ATENDIMENTO DAS CHAMADAS RECEBIDAS PELA CENTRAL DE REGULACAO DAS URGENCIAS COM ORIENTAC"""

dados1 = "https://raw.githubusercontent.com/JoaoVGuerra06/PesquisaDataSus/main/SAMU%20192%3A%20ATENDIMENTO%20DAS%20CHAMADAS%20RECEBIDAS%20PELA%20CENTRAL%20DE%20REGULACAO%20DAS%20URGENCIAS%20COM%20ORIENTAC/anos20182020.csv"

dados2 = "https://raw.githubusercontent.com/JoaoVGuerra06/PesquisaDataSus/main/SAMU%20192%3A%20ATENDIMENTO%20DAS%20CHAMADAS%20RECEBIDAS%20PELA%20CENTRAL%20DE%20REGULACAO%20DAS%20URGENCIAS%20COM%20ORIENTAC/anos20232024.csv"

dados3 = "https://raw.githubusercontent.com/JoaoVGuerra06/PesquisaDataSus/main/SAMU%20192%3A%20ATENDIMENTO%20DAS%20CHAMADAS%20RECEBIDAS%20PELA%20CENTRAL%20DE%20REGULACAO%20DAS%20URGENCIAS%20COM%20ORIENTAC/meses20182020.csv"

dados4 = "https://raw.githubusercontent.com/JoaoVGuerra06/PesquisaDataSus/main/SAMU%20192%3A%20ATENDIMENTO%20DAS%20CHAMADAS%20RECEBIDAS%20PELA%20CENTRAL%20DE%20REGULACAO%20DAS%20URGENCIAS%20COM%20ORIENTAC/meses20232024.csv"



links = [
dados1,
dados2,
dados3,
dados4
]


df_tot2 = {}
dfs2 = {}

for link in links:

    nome = link.split("/")[-1].replace(".csv","")

    df = pd.read_csv(link, sep=";", skiprows=5, encoding="latin1")

    df_tot2[nome] = df
    dfs2[nome] = percapita(df, pop_capitais)


dfs2["anos_total"] = pd.concat(
    [df for nome, df in dfs2.items() if "ano" in nome],
    axis=1
)

dfs2["meses_total"] = pd.concat(
    [df for nome, df in dfs2.items() if "mes" in nome],
    axis=1
)

dfs2["anos_total"] = dfs2["anos_total"].loc[:, ~dfs2["anos_total"].columns.duplicated()]
dfs2["meses_total"] = dfs2["meses_total"].loc[:, ~dfs2["meses_total"].columns.duplicated()]


for nome, df in dfs2.items():
    print(nome, len(df))

""" ATENDIMENTO DE URGÊNCIA EM ATENÇÃO BÁSICA"""

 dados1 = "https://raw.githubusercontent.com/JoaoVGuerra06/PesquisaDataSus/main/SAMU%20192%3A%20ATENDIMENTO%20DAS%20CHAMADAS%20RECEBIDAS%20PELA%20CENTRAL%20DE%20REGULACAO%20DAS%20URGENCIAS%20COM%20ORIENTAC/anos20182020.csv"

 dados2 = "https://raw.githubusercontent.com/JoaoVGuerra06/PesquisaDataSus/main/SAMU%20192%3A%20ATENDIMENTO%20DAS%20CHAMADAS%20RECEBIDAS%20PELA%20CENTRAL%20DE%20REGULACAO%20DAS%20URGENCIAS%20COM%20ORIENTAC/anos20232024.csv"

 dados3 = "https://raw.githubusercontent.com/JoaoVGuerra06/PesquisaDataSus/main/SAMU%20192%3A%20ATENDIMENTO%20DAS%20CHAMADAS%20RECEBIDAS%20PELA%20CENTRAL%20DE%20REGULACAO%20DAS%20URGENCIAS%20COM%20ORIENTAC/meses20182020.csv"

 dados4 = "https://raw.githubusercontent.com/JoaoVGuerra06/PesquisaDataSus/main/SAMU%20192%3A%20ATENDIMENTO%20DAS%20CHAMADAS%20RECEBIDAS%20PELA%20CENTRAL%20DE%20REGULACAO%20DAS%20URGENCIAS%20COM%20ORIENTAC/meses20232024.csv"

 links = [
 dados1,
 dados2,
 dados3,
 dados4
 ]


 df_tot3 = {}
 dfs3 = {}

 for link in links:

     nome = link.split("/")[-1].replace(".csv","")

     df = pd.read_csv(link, sep=";", skiprows=5, encoding="latin1")

     df_tot3[nome] = df
     dfs3[nome] = percapita(df, pop_capitais)


 dfs3["anos_total"] = pd.concat(
     [df for nome, df in dfs3.items() if "ano" in nome],
     axis=1
 )

 dfs3["meses_total"] = pd.concat(
     [df for nome, df in dfs3.items() if "mes" in nome],
     axis=1
 )

 dfs3["anos_total"] = dfs3["anos_total"].loc[:, ~dfs3["anos_total"].columns.duplicated()]
 dfs3["meses_total"] = dfs3["meses_total"].loc[:, ~dfs3["meses_total"].columns.duplicated()]


 for nome, df in dfs3.items():
     print(nome, len(df))

"""ATENDIMENTO DE URGENCIA EM ATENÇÃO ESPECIALIZADA"""

# dados1 = ""

# dados2 = ""

# dados3 = ""

# dados4 = ""



# links = [
# dados1,
# dados2,
# dados3,
# dados4
# ]


# df_tot4 = {}
# dfs4 = {}

# for link in links:

#     nome = link.split("/")[-1].replace(".csv","")

#     df = pd.read_csv(link, sep=";", skiprows=5, encoding="latin1")

#     df_tot4[nome] = df
#     dfs4[nome] = percapita(df, pop_capitais)


# dfs4["anos_total"] = pd.concat(
#     [df for nome, df in dfs4.items() if "ano" in nome],
#     axis=1
# )

# dfs4["meses_total"] = pd.concat(
#     [df for nome, df in dfs4.items() if "mes" in nome],
#     axis=1
# )

# dfs4["anos_total"] = dfs4["anos_total"].loc[:, ~dfs4["anos_total"].columns.duplicated()]
# dfs4["meses_total"] = dfs4["meses_total"].loc[:, ~dfs4["meses_total"].columns.duplicated()]


# for nome, df in dfs4.items():
#     print(nome, len(df))

"""ATENDIMENTO DE URGENCIA EM ATENÇÃO PRIMÁRIA COM OBSERVAÇÃO ATÉ 8 HORAS"""

# dados1 = ""

# dados2 = ""

# dados3 = ""

# dados4 = ""


# links = [
# dados1,
# dados2,
# dados3,
# dados4
# ]


# df_tot5 = {}
# dfs5 = {}

# for link in links:

#     nome = link.split("/")[-1].replace(".csv","")

#     df = pd.read_csv(link, sep=";", skiprows=5, encoding="latin1")

#     df_tot5[nome] = df
#     dfs5[nome] = percapita(df, pop_capitais)


# dfs5["anos_total"] = pd.concat(
#     [df for nome, df in dfs5.items() if "ano" in nome],
#     axis=1
# )

# dfs5["meses_total"] = pd.concat(
#     [df for nome, df in dfs5.items() if "mes" in nome],
#     axis=1
# )

# dfs5["anos_total"] = dfs5["anos_total"].loc[:, ~dfs5["anos_total"].columns.duplicated()]
# dfs5["meses_total"] = dfs5["meses_total"].loc[:, ~dfs5["meses_total"].columns.duplicated()]


# for nome, df in dfs5.items():
#     print(nome, len(df))

"""ATENDIMENTO DE URGENCIA EM ATENÇÃO PRIMÁRIA COM REMOÇÃO"""

# dados1 = ""

# dados2 = ""

# dados3 = ""

# dados4 = ""


# links = [
# dados1,
# dados2,
# dados3,
# dados4
# ]


# df_tot6 = {}
# dfs6 = {}

# for link in links:

#     nome = link.split("/")[-1].replace(".csv","")

#     df = pd.read_csv(link, sep=";", skiprows=5, encoding="latin1")

#     df_tot6[nome] = df
#     dfs6[nome] = percapita(df, pop_capitais)


# dfs6["anos_total"] = pd.concat(
#     [df for nome, df in dfs6.items() if "ano" in nome],
#     axis=1
# )

# dfs6["meses_total"] = pd.concat(
#     [df for nome, df in dfs6.items() if "mes" in nome],
#     axis=1
# )

# dfs6["anos_total"] = dfs6["anos_total"].loc[:, ~dfs6["anos_total"].columns.duplicated()]
# dfs6["meses_total"] = dfs6["meses_total"].loc[:, ~dfs6["meses_total"].columns.duplicated()]


# for nome, df in dfs6.items():
#     print(nome, len(df))

"""ATENDIMENTO DE URGÊNCIA EM PEQUENO QUEIMADO"""

# dados1 = ""

# dados2 = ""

# dados3 = ""

# dados4 = ""

# links = [
# dados1,
# dados2,
# dados3,
# dados4
# ]


# df_tot7 = {}
# dfs7 = {}

# for link in links:

#     nome = link.split("/")[-1].replace(".csv","")

#     df = pd.read_csv(link, sep=";", skiprows=5, encoding="latin1")

#     df_tot7[nome] = df
#     dfs7[nome] = percapita(df, pop_capitais)


# dfs7["anos_total"] = pd.concat(
#     [df for nome, df in dfs7.items() if "ano" in nome],
#     axis=1
# )

# dfs7["meses_total"] = pd.concat(
#     [df for nome, df in dfs7.items() if "mes" in nome],
#     axis=1
# )

# dfs7["anos_total"] = dfs7["anos_total"].loc[:, ~dfs7["anos_total"].columns.duplicated()]
# dfs7["meses_total"] = dfs7["meses_total"].loc[:, ~dfs7["meses_total"].columns.duplicated()]


# for nome, df in dfs7.items():
#     print(nome, len(df))

"""MATRICIAMENTO DE EQUIPES DOS PONTOS DE ATENÇÃO DA URGENCIA E EMERGÊNCIA, E DOS SERVIÇOS HOSPITAL"""

# dados1 = ""

# dados2 = ""

# dados3 = ""

# dados4 = ""


# links = [
# dados1,
# dados2,
# dados3,
# dados4
# ]


# df_tot8 = {}
# dfs8 = {}

# for link in links:

#     nome = link.split("/")[-1].replace(".csv","")

#     df = pd.read_csv(link, sep=";", skiprows=5, encoding="latin1")

#     df_tot8[nome] = df
#     dfs8[nome] = percapita(df, pop_capitais)


# dfs8["anos_total"] = pd.concat(
#     [df for nome, df in dfs8.items() if "ano" in nome],
#     axis=1
# )

# dfs8["meses_total"] = pd.concat(
#     [df for nome, df in dfs8.items() if "mes" in nome],
#     axis=1
# )

# dfs8["anos_total"] = dfs8["anos_total"].loc[:, ~dfs8["anos_total"].columns.duplicated()]
# dfs8["meses_total"] = dfs8["meses_total"].loc[:, ~dfs8["meses_total"].columns.duplicated()]


# for nome, df in dfs8.items():
#     print(nome, len(df))

"""REGULAÇÃO MÉDICA DE URGENCIA DA CENTRAL SAMU 192 Com ACIONAMENTO DE MULTIPLOS MEIOS

"""

# dados1 = ""

# dados2 = ""

# dados3 = ""

# dados4 = ""


# links = [
# dados1,
# dados2,
# dados3,
# dados4
# ]


# df_tot9 = {}
# dfs9 = {}

# for link in links:

#     nome = link.split("/")[-1].replace(".csv","")

#     df = pd.read_csv(link, sep=";", skiprows=5, encoding="latin1")

#     df_tot9[nome] = df
#     dfs9[nome] = percapita(df, pop_capitais)


# dfs9["anos_total"] = pd.concat(
#     [df for nome, df in dfs9.items() if "ano" in nome],
#     axis=1
# )

# dfs9["meses_total"] = pd.concat(
#     [df for nome, df in dfs9.items() if "mes" in nome],
#     axis=1
# )

# dfs9["anos_total"] = dfs9["anos_total"].loc[:, ~dfs9["anos_total"].columns.duplicated()]
# dfs9["meses_total"] = dfs9["meses_total"].loc[:, ~dfs9["meses_total"].columns.duplicated()]


# for nome, df in dfs9.items():
#     print(nome, len(df))

"""TENECTEPLASE 40 MG INJETAVEL (POR FRASCO AMPOLA) DE USO NAS URGÊNCIAS PRÉ-HOSPITALARES"""

# dados1 = ""

# dados2 = ""

# dados3 = ""

# dados4 = ""

# links = [
# dados1,
# dados2,
# dados3,
# dados4
# ]


# df_tot10 = {}
# dfs10 = {}

# for link in links:

#     nome = link.split("/")[-1].replace(".csv","")

#     df = pd.read_csv(link, sep=";", skiprows=5, encoding="latin1")

#     df_tot10[nome] = df
#     dfs10[nome] = percapita(df, pop_capitais)


# dfs10["anos_total"] = pd.concat(
#     [df for nome, df in dfs10.items() if "ano" in nome],
#     axis=1
# )

# dfs10["meses_total"] = pd.concat(
#     [df for nome, df in dfs10.items() if "mes" in nome],
#     axis=1
# )

# dfs10["anos_total"] = dfs10["anos_total"].loc[:, ~dfs10["anos_total"].columns.duplicated()]
# dfs10["meses_total"] = dfs10["meses_total"].loc[:, ~dfs10["meses_total"].columns.duplicated()]


# for nome, df in dfs10.items():
#     print(nome, len(df))

"""TENECTEPLASE 50 MG INJETAVEL (POR FRASCO AMPOLA) DE USO NAS URGÊNCIAS PRÉ-HOSPITALARES"""

# dados1 = ""

# dados2 = ""

# dados3 = ""

# dados4 = ""


# links = [
# dados1,
# dados2,
# dados3,
# dados4
# ]


# df_tot11 = {}
# dfs11 = {}

# for link in links:

#     nome = link.split("/")[-1].replace(".csv","")

#     df = pd.read_csv(link, sep=";", skiprows=5, encoding="latin1")

#     df_tot11[nome] = df
#     dfs11[nome] = percapita(df, pop_capitais)


# dfs11["anos_total"] = pd.concat(
#     [df for nome, df in dfs11.items() if "ano" in nome],
#     axis=1
# )

# dfs11["meses_total"] = pd.concat(
#     [df for nome, df in dfs11.items() if "mes" in nome],
#     axis=1
# )

# dfs11["anos_total"] = dfs11["anos_total"].loc[:, ~dfs11["anos_total"].columns.duplicated()]
# dfs11["meses_total"] = dfs11["meses_total"].loc[:, ~dfs11["meses_total"].columns.duplicated()]


# for nome, df in dfs11.items():
#     print(nome, len(df))

"""APOIO MATRICIAL EM SAUDE DO TRABALHADOR NA ATENÇÃO ESPECIALIZADA, URGENCIA E EMERGÊNCIA"""

# dados1 = ""

# dados2 = ""

# dados3 = ""

# dados4 = ""


# links = [
# dados1,
# dados2,
# dados3,
# dados4
# ]


# df_tot12 = {}
# dfs12 = {}

# for link in links:

#     nome = link.split("/")[-1].replace(".csv","")

#     df = pd.read_csv(link, sep=";", skiprows=5, encoding="latin1")

#     df_tot12[nome] = df
#     dfs12[nome] = percapita(df, pop_capitais)


# dfs12["anos_total"] = pd.concat(
#     [df for nome, df in dfs12.items() if "ano" in nome],
#     axis=1
# )

# dfs12["meses_total"] = pd.concat(
#     [df for nome, df in dfs12.items() if "mes" in nome],
#     axis=1
# )

# dfs12["anos_total"] = dfs12["anos_total"].loc[:, ~dfs12["anos_total"].columns.duplicated()]
# dfs12["meses_total"] = dfs12["meses_total"].loc[:, ~dfs12["meses_total"].columns.duplicated()]


# for nome, df in dfs12.items():
#     print(nome, len(df))

"""ATENDIMENTO DE URGENCIA Com OBSERVAÇÃO ATE 24 HORAS EM ATENÇÃO ESPECIALIZADA"""

# dados1 = ""

# dados2 = ""

# dados3 = ""

# dados4 = ""


# links = [
# dados1,
# dados2,
# dados3,
# dados4
# ]


# df_tot12 = {}
# dfs12 = {}

# for link in links:

#     nome = link.split("/")[-1].replace(".csv","")

#     df = pd.read_csv(link, sep=";", skiprows=5, encoding="latin1")

#     df_tot12[nome] = df
#     dfs12[nome] = percapita(df, pop_capitais)


# dfs12["anos_total"] = pd.concat(
#     [df for nome, df in dfs12.items() if "ano" in nome],
#     axis=1
# )

# dfs12["meses_total"] = pd.concat(
#     [df for nome, df in dfs12.items() if "mes" in nome],
#     axis=1
# )

# dfs12["anos_total"] = dfs12["anos_total"].loc[:, ~dfs12["anos_total"].columns.duplicated()]
# dfs12["meses_total"] = dfs12["meses_total"].loc[:, ~dfs12["meses_total"].columns.duplicated()]


# for nome, df in dfs12.items():
#     print(nome, len(df))

"""***
# <font size = 12 color = royalblue> APLICAÇÕES NOS PROCEDIMENTOS </font>
***

## SAMU 192:ATENDIMENTO DAS CHAMADAS RECEBIDAS PELA CENTRAL DE REGULAÇÃO DAS URGÊNCIAS
"""

#plot_todos(dfs1, cod_capitais)

"""## SAMU 192: ATENDIMENTO DAS CHAMADAS RECEBIDAS PELA CENTRAL DE REGULACAO DAS URGENCIAS COM ORIENTAC"""
#t_todos(dfs2, cod_capitais)#
